yatube/about/urls.py
from . import views

from django.urls import path

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'
         ),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name='Название публикации')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group', blank=True,
        on_delete=models.SET_NULL, null=True,
        related_name='group_posts',
        verbose_name='Группа',
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Изображение',
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий пользователя'
    )
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время публикации комментария'
    )

    def __str__(self) -> str:
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',

    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Подписка на авторов'
        verbose_name_plural = 'Подписки на авторов'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_author')
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        help_texts = {
            'text': ('Введите текст'),
            'group': ('Выберете группу'),
            'image': ('Загрузите файл')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        help_texts = {
            'text': ('Текст комментария'),
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, Follow, User
from .utils import get_paginator


@cache_page(20, key_prefix='index_page')
def index(request):
    return render(request,
                  'posts/index.html',
                  {'page_obj': get_paginator(
                   Post.objects.select_related('author',
                                               'group').all(), request)})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()
    context = {
        'group': group,
        'page_obj': get_paginator(posts, request),
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None
                    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    form.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not request.user == post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True,
        }
        return render(request, 'posts/create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all().select_related('author', 'post')
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.filter(author=author)
    context = {
        'author': author,
        'page_obj': get_paginator(posts, request),
        'following':
            request.user.is_authenticated
            and request.user != author
            and Follow.objects.filter(user=request.user, author=author)
    }
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': get_paginator(posts, request),
    }
    return render(
        request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    if request.user.username != username:
        Follow.objects.get_or_create(
            user=request.user,
            author=get_object_or_404(User,
                                     username=username))
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    user = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user,
                          author=user).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">

        {% if is_edit %}
          Редактировать пост  
        {% else %}
          Новый пост
        {% endif %}     

        </div>
          <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}        
            {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}

          {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_text }}">
              {{ field.label }}
            {% if field.field.required %}
            <span class="required text-danger" >*</span> 
            {% endif %}

          </label>
            {% load user_filters %}
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
              <small
              id="{{ field.id_for_label}}-help"
              class="form-text text-muted">
              {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
            {% endfor %}

            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                <span class="spark"></span>
                <span class="backdrop"></span>
                <svg class="sparkle" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M14.187 8.096L15 5.25L15.813 8.096C16.0231 8.83114 16.4171 9.50062 16.9577 10.0413C17.4984 10.5819 18.1679 10.9759 18.903 11.186L21.75 12L18.904 12.813C18.1689 13.0231 17.4994 13.4171 16.9587 13.9577C16.4181 14.4984 16.0241 15.1679 15.814 15.903L15 18.75L14.187 15.904C13.9769 15.1689 13.5829 14.4994 13.0423 13.9587C12.5016 13.4181 11.8321 13.0241 11.097 12.814L8.25 12L11.096 11.187C11.8311 10.9769 12.5006 10.5829 13.0413 10.0423C13.5819 9.50162 13.9759 8.83214 14.186 8.097L14.187 8.096Z" fill="black" stroke="black" stroke-linecap="round" stroke-linejoin="round" />
                  <path d="M6 14.25L5.741 15.285C5.59267 15.8785 5.28579 16.4206 4.85319 16.8532C4.42059 17.2858 3.87853 17.5927 3.285 17.741L2.25 18L3.285 18.259C3.87853 18.4073 4.42059 18.7142 4.85319 19.1468C5.28579 19.5794 5.59267 20.1215 5.741 20.715L6 21.75L6.259 20.715C6.40725 20.1216 6.71398 19.5796 7.14639 19.147C7.5788 18.7144 8.12065 18.4075 8.714 18.259L9.75 18L8.714 17.741C8.12065 17.5925 7.5788 17.2856 7.14639 16.853C6.71398 16.4204 6.40725 15.8784 6.259 15.285L6 14.25Z" fill="black" stroke="black" stroke-linecap="round" stroke-linejoin="round" />
                  <path d="M6.5 4L6.303 4.5915C6.24777 4.75718 6.15472 4.90774 6.03123 5.03123C5.90774 5.15472 5.75718 5.24777 5.5915 5.303L5 5.5L5.5915 5.697C5.75718 5.75223 5.90774 5.84528 6.03123 5.96877C6.15472 6.09226 6.24777 6.24282 6.303 6.4085L6.5 7L6.697 6.4085C6.75223 6.24282 6.84528 6.09226 6.96877 5.96877C7.09226 5.84528 7.24282 5.75223 7.4085 5.697L8 5.5L7.4085 5.303C7.24282 5.24777 7.09226 5.15472 6.96877 5.03123C6.84528 4.90774 6.75223 4.75718 6.697 4.5915L6.5 4Z" fill="black" stroke="black" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                {% if is_edit %}
                <span class="text">Сохранить</span>
                {% else %}
                <span class="text">Добавить</span>
                {% endif %}               
              </button> 
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</main>
{% endblock content%}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
<div class="container py-3">
<h2>
Избранное
</h2>
{% endblock title %}

{% block content %}
{% include "includes/switcher.html" with follow=True %}
{% for post in page_obj %}
{% include "includes/single_post.html" with show_post=True %}

{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

{% include "includes/paginator.html" %}
{% endblock content%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
<div class="container py-3">
  <h2>
Записи сообщества: {{ group.title }}
  </h2>
{% endblock %}
    
{% block content %}
<h2> 
  {{ group.title }}
</h2>
<p>
  <font size="5"> 
    Описание: {{ group.description|linebreaksbr }}
</font>
</p>

{% for post in page_obj %}
{% include "includes/single_post.html" with show_post=False %}

{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}

{% include "includes/paginator.html" %}

{% endblock content%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
<div class="container py-3">
<h2>
Лента публикаций
</h2>
{% endblock title %}

{% block content %}
{% include "includes/switcher.html" with index=True %}
{% cache 20 index_page page_obj.number %}
{% for post in page_obj %}
{% include "includes/single_post.html" with show_post=True %}

{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
{% endcache %}
{% include "includes/paginator.html" %}
{% endblock content%}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
<div class="container py-3">
  <h2>
    Пост: {{ post.text|truncatechars:30 }} 
  </h2>
{% endblock %}

{% block content %}
  <div class="row">
      <ul class="list-group list-group-flush">
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}   
        <li>
          Группа: {{ post.group.title }}
        </li>
        <li>
          <a 
          href="{% url 'posts:group_list' post.group.slug %}"
          >
         Все записи группы
        </a>
        </li>
        {% endif %}
        <li>
           Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Всего постов автора:  <span > {{ post.author.posts.count }}</span>
        </li>
        <li>
          <a
         href="{% url 'posts:profile' post.author.username %}">
         Все посты пользователя
          </a>
      </li>
      </ul>
      {% thumbnail post.image "960x960" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author.pk == user.pk %}
        <a 
        class="btn btn-primary" 
        href="{% url 'posts:post_edit' post.id %}"
        >
          Редактировать запись
        </a>
      {% endif %}


      {% include "includes/comment.html" %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
<div class="container py-3">
  <h2>
Профиль пользователя @{{ author.get_full_name }}
  </h2>
{% endblock %}

{% block content %}
  <div class="mb-5">        
    <h3>
      Все посты пользователя: {{ author.get_full_name }}
    </h3>
    <h3>
      Всего постов: {{ author.posts.count }}
    </h3>
    {% if user.is_authenticated and author != user %}
    {% if following %}
      <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
      Отписаться
      </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
      Подписаться
      </a>
    {% endif %}
    {% endif %}
    <div class="container py-3">

{% for post in page_obj %}

{% include "includes/single_post.html" with show_post=False %}
        
{% if not forloop.last %}
  <hr>
{% endif %}
{% endfor %}
        
{% include "includes/paginator.html" %}
        
{% endblock content%}